version: '3'
services:
  ajenti-3-development-backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    image: ajenti-3-development-backend-image
    volumes:
      - ./.container/etc/:/etc/ajenti/
      - ./.container/config/:/root/.config/
      - ./:/opt/ajenti/backend/


