auth:
  allow_sudo: true
  emails: {}
  provider: os
  users:
    root:
      password: 73637279707400100000000800000001f77e545afaeced51bdc33d16311ae24d900fbd462f444bce13d3c2aec489f90996523b8f779955a0f67708e0164de989c91a9a8093cd422fd5f5727018bb790f8aa36363273f5415660e7ff5c9fb9432e1f8ef5a3e35604ab9f2549aa85dbf2ca842573d25c02753bee5f0dd9c542b5ec51d58b443ad9f5e2b8dd9de8bd63a70908a1283c290bc7ccab30a3a88553ef23f5a6c25ccbe82e9f2b9ea656a6e373c33897e7b6376992de5cd00e78ed940486cd7bf0634ab1a1be2cf2f14ba2beabd55f82f5f3859ee9eea350c0a9fa9495749f0d0d6db21c5c17c742263e0e5bfb5c1c964edec1579c92ea538566151581bd06756564c21796eb61a0dd6d42b95ea5b1cdf667e0b06450622882fbf0bc7c9274903fd920368742769ee70e24a6d917afe6ba28faca235bcb83a1e22f37ee867d843b023424885623470940dd17c244a8f0ef998f29e5b680721d656c2a610609534e47ece10ea164b884d11ce983148aacf84044c5336bbc167fd28f45438
      uid: 0
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
color: bluegrey
language: ru
max_sessions: 9
name: Test Box
restricted_user: nobody
ssl:
  certificate: /etc/ajenti/ajenti.pem
  client_auth:
    certificates:
    - digest: 5F:C9:F2:8E:25:AC:D2:72:1B:B1:44:08:53:A7:11:9C:01:6C:D8:02
      name: C=NA,ST=NA,O=Test Box,CN=root@eugene-thinkpad
      serial: 5.458284616303889e+47
      user: root
    enable: true
    force: false
  enable: false
